kind: Service
apiVersion: v1
metadata:
  name: jobin-job-service
  namespace: kubernetes-service-account-ns
spec:
  selector:
    app: jobin-job-service
    tier: backend
  ports:
    - protocol: TCP
      port: 4011
      targetPort: 4011
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobin-job-service
  namespace: kubernetes-service-account-ns
  labels:
    app: jobin-job-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobin-job-service
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: jobin-job-service
        tier: backend
        track: stable
    spec:
      #      https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#gcloud_3
      serviceAccountName: jobin-cluster-ksa
      containers:
        - name: jobin-job-service
          # noinspection KubernetesUnknownValues
          image: LOCATION-docker.pkg.dev/PROJECT_ID/jobin-cloud/REPOSITORY:TAG
          resources:
            requests:
              memory: "200Mi" # 512Mi
              cpu: "100m" # 250m
              ephemeral-storage: "0.1Gi" # 0.5Gi
          readinessProbe:
            httpGet:
              path: /jobin-job-service/health
              port: 4011
            initialDelaySeconds: 1 # default 0
            periodSeconds: 10 # default 10
            timeoutSeconds: 1 # default 1
          livenessProbe:
            httpGet:
              path: /jobin-job-service/health
              port: 4011
            initialDelaySeconds: 1 # default 0
            periodSeconds: 10 # default 10
            timeoutSeconds: 1 # default 1
#          startupProbe:
#            httpGet:
#              path: /jobin-job-service/gc-health
#              port: 4011
#            initialDelaySeconds: 0 # default 0
#            periodSeconds: 10 # default 10
#            timeoutSeconds: 1 # default 1
#            failureThreshold: 15
          ports:
            - containerPort: 4011
      #          lifecycle:
      #            preStop:
      #              exec:
      #                command: [
      #                  "sh", "-c",
      #                  # Introduce a delay to the shutdown sequence to wait for the
      #                  # pod eviction event to propagate. Then, gracefully shutdown
      #                  # nginx.
      #                  # "sleep 5 && /usr/bin/nodejs -s quit",
      #                  "sleep 5",
      #                ]